=== sindycarlo/progetto-tecweb/xml/parte XML/4forchette.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.4forchette.com"
xmlns="http://www.4forchette.com"
elementFormDefault="qualified"> <!-- modificare -->
<xsd:element name="database">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element ref="ricetteDB"/>
			<xsd:element ref="utentiDB"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="ricetteDB">
	<xsd:complexType>
		<xsd:element ref="ricetta" maxOccurs="unbounded"/>
	</xsd:complexType>
</xsd:element>

<xsd:element name="utentiDB">
	<xsd:complexType>
		<xsd:element ref="utente" maxOccurs="unbounded"/>
	</xsd:complexType>
</xsd:element>

<xsd:element name="ricetta">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="nomePiatto" type="xsd:string"/>
			<xsd:element name="autore" type="xsd:string"/>
			<xsd:element name="descrizione" type="xsd:string"/>
			<xsd:element name="imgPiatto" type="xsd:string"/>
			<xsd:element name="difficolta" type="xsd:short"/> <!-- poi stampiamo come difficolta + /3 -->
			<xsd:element name="valutazioneUtenti" type="xsd:short"/>
			<xsd:element name="quantePersone" type="xsd:short"/>
			<xsd:element name="ingredienti">
				<xsd:complexType>
					<xsd:element ref="ingr" minOccurs="1" maxOccurs="unbounded"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="tempoPreparazione" type="tempo"/>
			<xsd:element name="tempoCottura" type="tempo"/>
			<xsd:element name="procedimento" type="xsd:string"/>			
			<xsd:element name="tag" minOccurs="1" maxOccurs="unbounded" type="xsd:string"/>
			<xsd:element name="commenti">
				<xsd:complexType>
					<xsd:element ref="post" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="ingr" type="xsd:string"/>

<xsd:element name="tempo">
	<xsd:complexType>
		<xsd:simpleContent>
			<xsd:extension base="xsd:short">
				<xsd:attribute name="unitaMisura" type="xsd:string"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:element>

<xsd:element name="post">
	<xsd:complexType>
		<xsd:element name="autore" type="xsd:string"/>
		<xsd:element name="data" type="xsd:date"/>
		<xsd:element name="testo" type="xsd:string"/>
	</xsd:complexType>
</xsd:element>

<xsd:element name="utente">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="mail" type="xsd:string"/>
			<xsd:element name="pwd" type="xsd:string"/>
			<xsd:element name="nome" type="xsd:string"/>
			<xsd:element name="cognome" type="xsd:string"/>
			<xsd:element name="dataNascita" type="xsd:date"/>
			<xsd:element name="username" type="xsd:string"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

</xsd:schema>
<!-- by Alessio Luca Last Update 01/12/2015-->

=== sindycarlo/progetto-tecweb/xml/parte XML/4forchette.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="4forchette.xsl"?>
<ricetteDB xmlns="http://www.4forchette.com"
xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
xsd:schemaLocation="4forchette.xsd"> <!-- non so bene che valori bisogna sostiture in questi attributi -->
		<ricetta>
			<nomePiatto>Risotto agli asparagi</nomePiatto>
			<categoria>Primo</categoria>
			<autore>WWW.MISYA.INFO</autore>
			<descrizione>
				Il risotto agli asparagi e' una tipica ricetta primaverile,la prima ricetta con
				gli asparagi che trovate sul mio blog e questo perché sono i nemici giurati di
				mio marito, odia gli asparagi più di quanto non odi i carciofi e ho detto tutto!
				Indovinate invece chi è un'estimatrice degli asparagi? La mia piccola
				meraviglia, che ha apprezzato e ha condiviso con me il mio piatto di risotto
				agli asparagi, e queste sono soddisfazioni. Non so dalle vostre parti, ma qui a
				Napoli, o almeno a casa mia, gli asparagi non sono così radicati nelle nostre
				abitudini alimentari quindi ho iniziato con una cosa semplice come il risotto
				per poi preparare più in la' qualche altra cosina più sfiziosa. Bene, io vi
				saluto e vi auguro una buona giornata, bacibaci
			</descrizione>
			<imgPiatto>risotto.jpg</imgPiatto>
			<difficolta>1</difficolta>
			<quantePersone>4</quantePersone>
			<ingredienti>
				<ingr>300 gr di riso</ingr>
				<ingr>400 gr di asparagi</ingr>
				<ingr>1 litro di brodo vegetale</ingr>
				<ingr>1 scalogno</ingr> 
				<ingr>vino bianco</ingr>
				<ingr>40 gr di parmigiano</ingr> 
				<ingr>30 gr di burro</ingr> 
				<ingr>olio di oliva</ingr> 
				<ingr>sale</ingr> 
				<ingr>pepe bianco</ingr>
			</ingredienti>
			<tempoPreparazione unitaMisura="minuti">20</tempoPreparazione>	
			<procedimento>
				Pulite gli asparagi (clicca qui per vedere come pulire gli asparagi) e una volta
				mondati lessateli in acqua appena salata per 5 minuti. 
				Scolateli e tagliateli a pezzetti avendo cura di tenere da parte alcune punte
				per la decorazione finale del piatto.
				Nell'acqua in cui avrete cotto gli asparagi, aggiungete un dado vegetale (io uso
				quello fatto in casa) così da ottenere il brodo che vi servirà durante la cottura.
				Tritate lo scalogno finemente, mettetelo in una casseruola con l'olio e fatelo
				appassire
				Aggiungete il riso e fatelo tostare per un paio di minuti
				Quindi aggiungete il vino bianco e lasciatelo sfumate. 
				Aggiungete il brodo vegetale un mestolo per volta aggiungendolo man mano fino a
				cuocere completamente il riso.
				A metà cottura del risotto, aggiungete gli asparagi, aggiustate di sale e
				mescolare
				A fine cottura spegnete la fiamma e mantecate il risotto aggiungete burro e
				parmigiano
				Lasciar riposare il risotto agli asparagi un paio di minuti prima di servirlo
				guarnendo il piatto con pepe bianco e le punte degli asparagi che avevate tenuto
				da parte.
			</procedimento>
		</ricetta>
		<ricetta>
			<nomePiatto>Tiramisu'</nomePiatto>
			<categoria>Dessert</categoria>
			<autore>www.gustissimo.it</autore>
			<descrizione>
				Il tiramisù è un dolce diffuso in tutta Italia, le cui origini vengono spesso contese fra regioni quali il Veneto, il Friuli Venezia Giulia, il Piemonte e altre. È un dessert al cucchiaio a base di savoiardi, o altri biscotti di consistenza friabile, inzuppati nel caffè, mascarpone, uova e zucchero.
			</descrizione>			
			<imgPiatto>tiramisu.jpg</imgPiatto>
			<difficolta>1</difficolta>
			<quantePersone>8</quantePersone>
			<ingredienti>
				<ingr>600 gr. di Savoiardi</ingr>
				<ingr>120 gr. di Zucchero</ingr>
				<ingr>5 Uova</ingr>
				<ingr>500 gr. di Mascarpone</ingr>
				<ingr>Cacao in polvere q.b.</ingr>
				<ingr>Caffè q.b.</ingr>
				<ingr>30 ml di Rum</ingr>
			</ingredienti>
			<tempoPreparazione unitaMisura="minuti">30</tempoPreparazione>	
			<procedimento>
				Preparate un caffé con la moka, lasciatelo intiepidire e correggetelo col rum. Versatelo in una ciotola abbastanza larga da poterci inzuppare i savoiardi uno ad uno. Adagiate i biscotti in una vaschetta di plastica (in commercio troverete facilmente quelle fatte apposta per il tiramisù) foderando completamente il fondo.
				Sbattete i tuorli delle uova con metà dello zucchero, aggiungete il mascarpone e mescolate con un cucchiaio di legno fino ad ottenere un composto ben amalgamato.
				Montate a parte gli albumi montati a neve e lo zucchero restante. Incorporate il tutto delicatamente.
				A questo punto avrete ottenuto una crema che distenderete con l’aiuto di un cucchiaio o di una spatola a formare uno strato sopra i savoiardi.
				Coprite il tutto con una spolverata di cacao in polvere aiutandovi con un colino, poi procedete a formare un altro strato di savoiardi e crema.
				Riponete in frigorifero a riposare per qualche ora.
				Al momento di servire ricoprite il vostro tiramisù con un’ultima abbondante spolverata di cacao in polvere.				
				I savoiardi vanno intinti nel caffé molto velocemente, per evitare che si impregnino troppo e si sbriciolino.
				Amalgamando i vari ingredienti, usate l’accortezza di mescolare sempre nello stesso verso.
				Le uova devono essere freschissime.
				Se amate i sapori amari, potete aggiungere alla polvere di cacao anche un po’ di polvere di caffé.
				Con l’aiuto di sagome di cartone potete decorare a piacimento la superficie del dolce, anche con scritte di auguri.
			</procedimento>
		</ricetta>
	</ricetteDB>

<!-- by Alessio Luca Last Update 05/04/2016 -->

=== sindycarlo/progetto-tecweb/xml/4forchette.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<ricetteDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" 4forchette.xsd"><!-- non so bene che valori bisogna sostiture in questi attributi -->
		<ricetta IDCode="1"><!--credo che vada messo un codice identificativo per ogni ricetta-->
			<nomePiatto>Risotto agli asparagi</nomePiatto>
			<categoria>Primo</categoria>
			<autore>WWW.MISYA.INFO</autore>
			<descrizione>
				Il risotto agli asparagi e' una tipica ricetta primaverile,la prima ricetta con
				gli asparagi che trovate sul mio blog e questo perch√© sono i nemici giurati di
				mio marito, odia gli asparagi pi√π di quanto non odi i carciofi e ho detto tutto!
				Indovinate invece chi e' un'estimatrice degli asparagi? La mia piccola
				meraviglia, che ha apprezzato e ha condiviso con me il mio piatto di risotto
				agli asparagi, e queste sono soddisfazioni. Non so dalle vostre parti, ma qui a
				Napoli, o almeno a casa mia, gli asparagi non sono cosi' radicati nelle nostre
				abitudini alimentari quindi ho iniziato con una cosa semplice come il risotto
				per poi preparare piu' in la' qualche altra cosina piu' sfiziosa. Bene, io vi
				saluto e vi auguro una buona giornata, bacibaci
			</descrizione>
			<imgPiatto>risottoasparagi.jpg</imgPiatto>
			<difficolta>1</difficolta>
			<quantePersone>4</quantePersone>
			<ingredienti>
				<ingr>300 gr di riso</ingr>
				<ingr>400 gr di asparagi</ingr>
				<ingr>1 litro di brodo vegetale</ingr>
				<ingr>1 scalogno</ingr>
				<ingr>vino bianco</ingr>
				<ingr>40 gr di parmigiano</ingr>
				<ingr>30 gr di burro</ingr>
				<ingr>olio di oliva</ingr>
				<ingr>sale</ingr>
				<ingr>pepe bianco</ingr>
			</ingredienti>
			<tempoPreparazione unitaMisura="minuti">20</tempoPreparazione>
			<procedimento>
				Pulite gli asparagi e una volta
				mondati lessateli in acqua appena salata per 5 minuti.
				Scolateli e tagliateli a pezzetti avendo cura di tenere da parte alcune punte
				per la decorazione finale del piatto.
				Nell'acqua in cui avrete cotto gli asparagi, aggiungete un dado vegetale (io uso
				quello fatto in casa) cosi' da ottenere il brodo che vi servira' durante la cottura.
				Tritate lo scalogno finemente, mettetelo in una casseruola con l'olio e fatelo
				appassire
				Aggiungete il riso e fatelo tostare per un paio di minuti
				Quindi aggiungete il vino bianco e lasciatelo sfumate.
				Aggiungete il brodo vegetale un mestolo per volta aggiungendolo man mano fino a
				cuocere completamente il riso.
				A meta' cottura del risotto, aggiungete gli asparagi, aggiustate di sale e
				mescolare
				A fine cottura spegnete la fiamma e mantecate il risotto aggiungete burro e
				parmigiano
				Lasciar riposare il risotto agli asparagi un paio di minuti prima di servirlo
				guarnendo il piatto con pepe bianco e le punte degli asparagi che avevate tenuto
				da parte.
			</procedimento>
		</ricetta>
		<ricetta IDCode="2">
			<nomePiatto>Tiramisu'</nomePiatto>
			<categoria>Dessert</categoria>
			<autore>www.gustissimo.it</autore>
			<descrizione>
				Il tiramis√π e' un dolce diffuso in tutta Italia, le cui origini vengono spesso contese fra regioni quali il Veneto, il Friuli Venezia Giulia, il Piemonte e altre. √à un dessert al cucchiaio a base di savoiardi, o altri biscotti di consistenza friabile, inzuppati nel caffe'
			  , mascarpone, uova e zucchero.
			</descrizione>
			<imgPiatto>tiramisu.jpg</imgPiatto>
			<difficolta>1</difficolta>
			<quantePersone>8</quantePersone>
			<ingredienti>
				<ingr>600 gr. di Savoiardi</ingr>
				<ingr>120 gr. di Zucchero</ingr>
				<ingr>5 Uova</ingr>
				<ingr>500 gr. di Mascarpone</ingr>
				<ingr>Cacao in polvere q.b.</ingr>
				<ingr>Caffe' q.b.</ingr>
				<ingr>30 ml di Rum</ingr>
			</ingredienti>
			<tempoPreparazione unitaMisura="minuti">30</tempoPreparazione>
			<procedimento>
				Preparate un caffe' con la moka, lasciatelo intiepidire e correggetelo col rum. Versatelo in una ciotola abbastanza larga da poterci inzuppare i savoiardi uno ad uno. Adagiate i biscotti in una vaschetta di plastica (in commercio troverete facilmente quelle fatte apposta per il tiramis√π) foderando completamente il fondo.
				Sbattete i tuorli delle uova con met√† dello zucchero, aggiungete il mascarpone e mescolate con un cucchiaio di legno fino ad ottenere un composto ben amalgamato.
				Montate a parte gli albumi montati a neve e lo zucchero restante. Incorporate il tutto delicatamente.
				A questo punto avrete ottenuto una crema che distenderete con l‚Äôaiuto di un cucchiaio o di una spatola a formare uno strato sopra i savoiardi.
				Coprite il tutto con una spolverata di cacao in polvere aiutandovi con un colino, poi procedete a formare un altro strato di savoiardi e crema.
				Riponete in frigorifero a riposare per qualche ora.
				Al momento di servire ricoprite il vostro tiramis√π con un‚Äôultima abbondante spolverata di cacao in polvere.
				I savoiardi vanno intinti nel caff√© molto velocemente, per evitare che si impregnino troppo e si sbriciolino.
				Amalgamando i vari ingredienti, usate l‚Äôaccortezza di mescolare sempre nello stesso verso.
				Le uova devono essere freschissime.
				Se amate i sapori amari, potete aggiungere alla polvere di cacao anche un po‚Äô di polvere di caff√©.
				Con l‚Äôaiuto di sagome di cartone potete decorare a piacimento la superficie del dolce, anche con scritte di auguri.
			</procedimento>
		</ricetta>
  		<ricetta IDCode="3">
			<nomePiatto>Pasta con crema ai carciofi</nomePiatto>
			<categoria>Primo</categoria>
			<autore>WWW.MISYA.INFO</autore>
			<descrizione>
			Buond√¨, questa domenica vi propongo la pasta con crema di carciofi e pancetta croccante,
			un primo piatto che adoro ma che non preparo quasi mai perch√© Ivano detesta i carciofi.
			Ma quando a pranzo trovo la giusta compagnia, questo e‚Äô uno dei modi di utilizzare i carciofi che preferisco
		        e ho scoperto che la pasta condita con la crema di carciofi piace anche alla piccola.
			Amiche spero che abbiate trascorso un buon San Valentino e di essere riuscita anche quest‚Äôanno a darvi
		        qualche spunto in pi√π in cucina, noi ieri sera alla fine, dopo una giornata fuori casa,
			abbiamo cenato con pizza, birra e baci perugina üòâ Oggi, vista la pioggia, siamo casalinghi,
			per il momento siamo ancora a letto a vedere i cartoni animati, quindi vi lascio alla ricetta di oggi
			e vado a spupazzarmi i miei amori. Buona domenica a chi passa si qui
			</descrizione>
			<imgPiatto>cremacarciofi.jpg</imgPiatto>
			<difficolta>2</difficolta>
			<quantePersone>4</quantePersone>
			<ingredienti>
				<ingr>4 carciofi</ingr>
				<ingr>320gr di pasta</ingr>
				<ingr>1/2 cipolla</ingr>
				<ingr>200ml di brodo vegetale</ingr>
				<ingr>25gr di parmiggiano</ingr>
				<ingr>50gr di pancetta</ingr>
				<ingr>prezzemolo</ingr>
				<ingr>olio di oliva</ingr>
				<ingr>sale</ingr>
				<ingr>pepe</ingr>
			  	<ingr>1/2 limone</ingr>
			</ingredienti>
			<tempoPreparazione unitaMisura="minuti">20</tempoPreparazione>
			<procedimento>
			Pulite i carciofi. Poi tagliateli a spicchietti, e metteteli in acqua
			  e limone per 30 minuti. Tritate la cipolla e mettetela nella padella
			  con l'olio, poi aggiungete i carciofi, salate
			  e fate insaporire per qualche minuto. Aggiungete il prezzemolo,
			  coprite con il brodo e fate cuocere con il coperchio per 10 minuti circa.
			  Frullate tutto con un mixer poi aggiungete il parmiggiano.
			  Nel frattempo cuocete la pasta in abbondante acqua salata, scolate al dente
			  e versante in padella con il condimento.
			  Rosolate i cubetti di pancetta in padella,servite la pasta con crema di carciofi nei piatti
			  aggiungendo prezzemolo tritato e cubetti di pancetta croccanti
			</procedimento>
		</ricetta>
	</ricetteDB>

<!-- by Luca  Last Update 14/04/2016 -->
