=== sindycarlo/progetto-tecweb/data/4forchette.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.4forchette.com"
xmlns="http://www.4forchette.com"
elementFormDefault="qualified">

<xsd:element name="ricetteDB">
	<xsd:complexType>
		<xsd:element ref="ricetta" maxOccurs="unbounded"/>
	</xsd:complexType>
</xsd:element>

<xsd:element name="ricetta">
	<xsd:complexType>
		<xsd:sequence>
			<xsd:element name="nomePiatto" type="xsd:string"/>
			<xsd:element name="categoria" type="xsd:string"/>  <!-- enumerazione antipasto / primo / secondo / dessert -->
			<xsd:element name="autore" type="xsd:string"/>
			<xsd:element name="descrizione" type="xsd:string"/>
			<xsd:element name="imgPiatto" type="xsd:string"/>
			<xsd:element name="difficolta" type="xsd:short"/> <!-- poi stampiamo come difficolta + /3 -->
			<xsd:element name="quantePersone" type="xsd:short"/>
			<xsd:element name="ingredienti">
				<xsd:complexType>
					<xsd:element ref="ingr" minOccurs="1" maxOccurs="unbounded"/>
				</xsd:complexType>
			</xsd:element>
			<!-- <xsd:element name="tempoPreparazione" type="tempo"/> -->
			<xsd;element name="tempoPreparazione" type="xsd:short"/>
			<xsd:element name="procedimento" type="xsd:string"/>			
		</xsd:sequence>
	</xsd:complexType>
</xsd:element>

<xsd:element name="ingr" type="xsd:string"/>

<!-- 
per il tempo di cottura alla fine lo consideriamo come uno short int senza farti il tipo apposta a parte
poi stampiamo sulla pagina il valore seguito da " minuti" e morta lÃ 
<xsd:element name="tempo">
	<xsd:complexType>
		<xsd:simpleContent>
			<xsd:extension base="xsd:short">
				<xsd:attribute name="unitaMisura" type="xsd:string"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:element>
-->

</xsd:schema>
<!-- by Alessio Luca Last Update 05/04/2016-->

=== sindycarlo/progetto-tecweb/data/4forchette.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<ricetteDB xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" 4forchette.xsd">
		
		<ricetta IDCode="2" accepted="1">
			<nomePiatto>Tiramisu'</nomePiatto>
			<categoria>Dessert</categoria>
			<autore>www.gustissimo.it</autore>
			<descrizione>
				Il tiramisù e' un dolce diffuso in tutta Italia, le cui origini vengono spesso contese fra regioni quali il Veneto, il Friuli Venezia Giulia, il Piemonte e altre. È un dessert al cucchiaio a base di savoiardi, o altri biscotti di consistenza friabile, inzuppati nel caffe'
			  , mascarpone, uova e zucchero.
			</descrizione>
			<imgPiatto>tiramisu.jpg</imgPiatto>
			<difficolta>1</difficolta>
			<quantePersone>8</quantePersone>
			<ingredienti>
				<ingr>600 gr. di Savoiardi</ingr>
				<ingr>120 gr. di Zucchero</ingr>
				<ingr>5 Uova</ingr>
				<ingr>500 gr. di Mascarpone</ingr>
				<ingr>Cacao in polvere q.b.</ingr>
				<ingr>Caffe' q.b.</ingr>
				<ingr>30 ml di Rum</ingr>
			</ingredienti>
			<tempoPreparazione>30</tempoPreparazione>
			<procedimento>
				Preparate un caffe' con la moka, lasciatelo intiepidire e correggetelo col rum. Versatelo in una ciotola abbastanza larga da poterci inzuppare i savoiardi uno ad uno. Adagiate i biscotti in una vaschetta di plastica (in commercio troverete facilmente quelle fatte apposta per il tiramisù) foderando completamente il fondo.
				Sbattete i tuorli delle uova con metà dello zucchero, aggiungete il mascarpone e mescolate con un cucchiaio di legno fino ad ottenere un composto ben amalgamato.
				Montate a parte gli albumi montati a neve e lo zucchero restante. Incorporate il tutto delicatamente.
				A questo punto avrete ottenuto una crema che distenderete con l’aiuto di un cucchiaio o di una spatola a formare uno strato sopra i savoiardi.
				Coprite il tutto con una spolverata di cacao in polvere aiutandovi con un colino, poi procedete a formare un altro strato di savoiardi e crema.
				Riponete in frigorifero a riposare per qualche ora.
				Al momento di servire ricoprite il vostro tiramisù con un’ultima abbondante spolverata di cacao in polvere.
				I savoiardi vanno intinti nel caffé molto velocemente, per evitare che si impregnino troppo e si sbriciolino.
				Amalgamando i vari ingredienti, usate l’accortezza di mescolare sempre nello stesso verso.
				Le uova devono essere freschissime.
				Se amate i sapori amari, potete aggiungere alla polvere di cacao anche un po’ di polvere di caffé.
				Con l’aiuto di sagome di cartone potete decorare a piacimento la superficie del dolce, anche con scritte di auguri.
			</procedimento>
		</ricetta>
  		
		
	<ricetta IDCode="5" accepted="1"><nomePiatto>torta di fragole e biscotti</nomePiatto><autore>salepepe.it</autore><descrizione>&#13;
L’Italia è famosa nel mondo per i numerosi dolci e dessert tipici della tradizione. Basta citare il tiramisù, golosità in grado di soddisfare il palato di tutti, il panettone o il pandoro, tipici nel periodo natalizio, o i tradizionali dolci del sud come la pastiera napoletana o la cassata siciliale. Impossibile dimenticare il carnevale, periodo perfetto per preparare ogni tipologia di dolce fritto come frappe o chiacchiere né i dolci al cucchiaio come il biancomangiare o il budino al cioccolato. E se i biscotti meritano un capitolo a parte, la bella stagione è subito sinonimo di gelati artigianali al pistacchio, alla crema o ai gusti più insoliti.</descrizione><tempoPreparazione>60</tempoPreparazione><difficolta>2</difficolta><quantePersone>4</quantePersone><imgPiatto>tortafragole.jpg</imgPiatto><categoria>Dessert</categoria><procedimento>Preparazione della torta di fragole e biscottini&#13;
&#13;
1) La lavorazione della ricetta della torta di fragole e biscottini inizia la sera prima con la preparazione della base per la mousse.&#13;
&#13;
2) Porta a ebollizione 4 dl di panna in una casseruola, con l’aggiunta di una stecca di vaniglia incisa, poi filtra, scioglici il cioccolato tritato grossolanamente e una volta tiepida mettila in frigorifero per una notte.&#13;
&#13;
3) Trascorso il tempo necessario, prendi i biscotti Digestive e sbriciolali in una terrina, poi lavorali insieme al burro morbido.&#13;
&#13;
Preparazione della base di torta di fragole e biscottini&#13;
&#13;
&#13;
1) Prendi uno stampo a cerniera foderato con carta da forno e mettici il composto della base di torta alle fragole ben livellato, poi conserva in frigorifero.&#13;
&#13;
2) Monta 4 dl di panna fredda per la farcitura, aggiungendo poco alla volta lo zucchero a velo, fino ad avere un composto fermo e sodo.&#13;
&#13;
3) Riprendi la base della mousse preparata il giorno prima e monta il mix di panna e cioccolato, poi versalo nello stampo sullo strato di biscotti, stendilo uniformemente con una spatola e riponilo in frigorifero per un'ora circa.&#13;
&#13;
4) Sforma la torta, coprila con la panna e allinea i biscotti a sigaretta lungo il bordo. Decora la superficie con fragole, lamponi e biscotti rotondi. Lascia riposare ancora in frigorifero per un'ora e poi servi la torta di fragole e biscottini.</procedimento><ingredienti><ingr>cioccolato 200gr</ingr><ingr>&#13;
burro 30gr</ingr><ingr>&#13;
lamponi 200gr</ingr><ingr>&#13;
zucchero a velo 80gr</ingr><ingr>&#13;
biscotti 110gr</ingr><ingr>&#13;
fragole 300gr</ingr></ingredienti></ricetta><ricetta IDCode="7" accepted="1"><nomePiatto>Prova da telefono</nomePiatto><autore>Luca</autore><descrizione>Dovrebbe funzionare tutto</descrizione><tempoPreparazione>40</tempoPreparazione><difficolta>2</difficolta><quantePersone>4</quantePersone><imgPiatto>1465290297464543692556.jpg</imgPiatto><categoria>Antipasti</categoria><procedimento>Bla bla bla</procedimento><ingredienti><ingr>&#13;
Bestemmie</ingr><ingr/><ingr>Carlo</ingr><ingr>&#13;
Perl</ingr></ingredienti></ricetta><ricetta IDCode="8" accepted="1"><nomePiatto>Gelato alla vaniglia con marmellata di rovi camemori</nomePiatto><autore>Enrico l&amp;#39;artista</autore><descrizione>Gelato alla vaniglia con marmellata di rovi camemori (more selvatiche)</descrizione><tempoPreparazione>70</tempoPreparazione><difficolta>2</difficolta><quantePersone>4</quantePersone><imgPiatto>gelatoallemore.jpg</imgPiatto><categoria>Dessert</categoria><procedimento>Lavare e pulire i frutti di bosco. Unirli allo zucchero in una padella abbastanza larga. Scuotere ogni tanto la padella, ma non mescolare. Lasciare la padella a raffreddare per due ore.&#13;
&#13;
Scaldare a fiamma bassa i frutti di bosco e lasciar sobbollire per 20 minuti. Rimuovere la schiuma.&#13;
&#13;
Versare il latte, la panna, i semi di vaniglia ed il baccello in una padella e portare lentamente ad ebollizione. Spegnere la fiamma e lasciar raffreddare per 15 minuti.&#13;
&#13;
In una ciotola grande, sbattere i tuorli e lo zucchero per qualche minuto. Rimuovere il baccello di vaniglia dalla padella e versare il composto liquido in quello delle uova, continuando a mescolare. Rimettere il tutto in padella e riscaldare dolcemente, continuare a mescolare e non lasciar bollire. Lasciar raffreddare e procedere a versare il composto nella gelatiera perch&amp;Atilde;&amp;copy; si ghiacci.</procedimento><ingredienti><ingr>&#13;
24 millilitri di Panna fresca</ingr><ingr>&#13;
4 Tuorlo d'uovo</ingr><ingr>&#13;
240 millilitri di Latte intero</ingr><ingr>&#13;
1.5  Vaniglia, un baccello raschiato</ingr><ingr>450 grammi di More</ingr><ingr>&#13;
490 grammi di Zucchero</ingr></ingredienti></ricetta><ricetta IDCode="9" accepted="1"><nomePiatto>D&amp;#39;Orata</nomePiatto><autore>Enrico l&amp;#39;artista</autore><descrizione>Filetto di orata marinato in olio al ginger e zafferano al profumo di aglio selvatico su soffice di patate allo Champagne e sale rosso delle Hawaii</descrizione><tempoPreparazione>12</tempoPreparazione><difficolta>3</difficolta><quantePersone>2</quantePersone><imgPiatto>dorata.jpg</imgPiatto><categoria>Secondi</categoria><procedimento>Per la marinatura dell&amp;#39;orata: squamate, eviscerate e sfilettate l&amp;#39;orata, tagliando poi i filetti a tocchetti. Massaggiate l&amp;#39;orata con il sale, il pepe, lo zafferano e i semi di papavero, ricoprite d&amp;#39;olio e lasciate marinare per una notte in frigorifero.&#13;
&#13;
Per il soffice di patate allo champagne. In poco olio saltate le patate tagliate a lamelle insieme ai fiori di aglio selvatico. Sfumate con lo champagne, e unite il peperoncino tritato. Portate a cottura allungando con acqua. Salate e pepate abbondantemente.&#13;
&#13;
Prepariamo il Soffice: frullatele le patate con il mascarpone, la panna e l&amp;#39;olio extra vergine a filo, fino ad ottenere una purea, se necessario salate e pepate.&#13;
Per l&amp;#39;orata in oliocottura: trasferite i tocchetti di orata in un pentolino stretto dai bordi alti, coprite con l&amp;#39;olio di marinatura e aggiungetene altro fino a coprirla, se necessario. Aggiungete ancora una manciata di sale affumicato e trasferite sul fuoco a fiamma bassissima, portate a cottura lentamente.&#13;
&#13;
Impiattiamo: scaldate a bagnomaria la crema di patate, appena sar&amp;Atilde;&amp;nbsp; ben calda disponetela alla base del piatto. Scolate i filetti d&amp;#39;orata dall&amp;#39;olio di cottura, e con delicatezza ricopriteli con la foglia d&amp;#39;oro. Adagiate i filetti sulla crema soffice di patate. Ultimate con una spolverata di sale rosso delle Hawaii, semi di papavero leggermente tostati e fiori eduli (io ho utilizzato fiori di trifoglio, croccanti freschi e dolciastri, e fiori di aglio selvatico).</procedimento><ingredienti><ingr>300 grammi di Orata selvatica, 2 filetti</ingr><ingr>&#13;
40 grammi di Mascarpone</ingr><ingr>&#13;
1 pizzico di Peperoni rossi</ingr><ingr>&#13;
15 grammi di Aglio, selvatico, mazzetto</ingr><ingr>&#13;
1 cucchiaio da tavola di Semi di papavero</ingr><ingr>&#13;
1 bicchiere di Champagne</ingr><ingr>&#13;
300 grammi di Patate bianche, a lamelle</ingr><ingr>&#13;
