=== sindycarlo/progetto-tecweb/esem/cose.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"

	elementFormDefault="qualified" >
	
	<xsd:element name="cose" type="Tcose"/>
		
	<xsd:complexType name="Tcose">
		<xsd:sequence maxOccurs="unbounded">
			<xsd:element name="thing" type="Tthing"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Tthing">
		<xsd:sequence>
			<xsd:element name="stuff" type="xsd:integer"/>
			<xsd:element name="blabla" type="xsd:string"/>
			<xsd:element name="contenuto" type="xsd:string"/> 
		</xsd:sequence>
		<xsd:attribute name="IDcode" type="Tid" use="required"/>			
	</xsd:complexType>

	<xsd:simpleType name="Tid">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="1"/>
			<xsd:maxInclusive value="999999"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== sindycarlo/progetto-tecweb/esem/cose.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="index.xsl"?>
<cose xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation=" cose.xsd">
	<thing IDcode="1">
		<stuff>100</stuff>
		<blabla>sticazzi</blabla>
		<contenuto>primo oggetto</contenuto>
	</thing>
	<thing IDcode="2">
		<stuff>120</stuff>
		<blabla>altre cose</blabla>
		<contenuto>secondo oggetto</contenuto>
	</thing>
	<thing IDcode="3">
		<stuff>1007777</stuff>
		<blabla>cose</blabla>
		<contenuto>vbb</contenuto>
	</thing>
	<thing IDcode="4">
		<stuff>10023423423</stuff>
		<blabla>blablablabla</blabla>
		<contenuto>eccetera</contenuto>
	</thing>
</cose>
